name: Tmate SSH Debug

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "50 */5 * * *"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install tmate
        run: sudo apt-get update && sudo apt-get install -y tmate

      - name: Start tmate session
        run: tmate -F
