name: Tmate Termux Session

on:
  workflow_dispatch:  # Cho phép chạy thủ công từ GitHub Actions

jobs:
  termux_tmate:
    runs-on: ubuntu-latest

    steps:
      - name: Cài đặt tmate
        run: sudo apt-get update && sudo apt-get install -y tmate

      - name: Chạy tmate -F (Giống Termux)
        run: tmate -F
        
