name: Tmate Debug Session

on:  
  workflow_dispatch: # Cho phép chạy thủ công từ GitHub Actions

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Thiết lập tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true  # Chỉ bạn có thể truy cập session
          
